

server
{
	host localhost;
	listen 21000;
	root www;
	index index.html;
	
	location /cgi-bin
	{
		allow GET POST;
		cgi php;
		cgi_path /bin/php-cgi;
	}

	location /test
	{
		root /videos;
		return 301 /other; this return will delete the file uploaded
	}
	location /other
	{
		root /videos;
		autoindex on;
	}
}
