server
{
	host localhost;
	listen 8080;
	root www;
	index index.html index.py;
	error_page 400 errors/400.html;
	error_page 403 errors/403.html;
	error_page 405 errors/405.html;
	error_page 404 errors/404.html;
	error_page 408 errors/408.html;
	
	server_name localhost oussama; 
	
	location /cgi-bin
	{
		allow GET POST;
		cgi py;
		cgi_path /usr/bin/python3;
	}

	location /other
	{
		allow GET POST DELETE;
		autoindex on;
		root /videos;
		upload /videos;
	}
	
	location /deny
	{
		allow NONE;
	}
}
