

server
{
	host 127.0.0.1;
	listen 8080;
	root www;
	index index.html;
	
	location /cgi-bin
	{
		allow GET POST DELETE;
		cgi php;
		cgi_path /bin/php-cgi;
	}

	location /test
	{
		root /videos;
		allow POST;
		upload uploads;
		return 301 /other; this return will delete the file uploaded
	}
	location /videos
	{
		allow POST GET;
		autoindex on;
		root dir; /dir same as dir both rooted to www/dir;
	}
	location /other
	{
		autoindex on;
		allow GET;
	}

	location /deny
	{
		allow POST;
		upload /videos;
		return /images/image.png;
	}
}
