# print("HTTP/1.1 200 asd\r")
# msg = "<html>"\
# 	"<head>"\
# 	"<title>My Web Page 404</title>"\
# 	"</head>"\
# 	"<body>"\
# 	"<h1>Hello, World!</h1>"\
# 	"<p>This is a simple HTML page generated by Python.</p>"\
# 	"</body>"\
# 	"</html>"
	
# # HTTP headers
# print("Content-Type: text/html\r")
# print(f"Content-Length: {len(msg) + 1}\r")  # The Content-Length is optional, it's good practice but not always required
# print("\r")  # Empty line indicates the end of headers
print("\r\n\r")
# print(msg)
# # HTML content