print("HTTP/1.1 200 OK\r")
msg = "<html>"\
	"<head>"\
	"<title>My Web Page</title>"\
	"</head>"\
	"<body>"\
	"<h1>Hello, World!</h1>"\
	"<p>This is a simple HTML page generated by Python.</p>"\
	"</body>"\
	"</html>"
	
# HTTP headers
print("\r")