# print("HTTP/1.1 200 OK\r")
msg = "<html>"\
	"<head>"\
	"<title>My Web Page</title>"\
	"</head>"\
	"<body>"\
	"<h1>Hello, World!</h1>"\
	"<p>This is a simple HTML page generated by Python.</p>"\
	"</body>"\
	"</html>"
	
# HTTP headers
# print("Content-Type: text/html\r")
# # print("Status: 200 OK\r")
print("Status: 200 OK\r")
# print(f"Content-Length: {len(msg) + 1}\r") 
print("\r") 
# print(msg)
